# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!


def networkPods
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.5.1'
end

def modelPods
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :tag => '3.1.4'
end


target 'App' do
    
    networkPods
    modelPods
    
end
